package com.selenium.studio.codegen;

import com.selenium.studio.model.TestConfig;
import com.selenium.studio.model.TestStep;

import java.util.List;

public class CodeGenerator {

    public static String generate(TestConfig cfg) {
        try {
            List<String>   browsers = cfg.getBrowsers();
            List<TestStep> steps    = cfg.getSteps();
            boolean headless = cfg.isHeadless();
            boolean maximize = cfg.isMaximize();
            boolean autoSS   = cfg.isAutoScreenshot();

            StringBuilder sb = new StringBuilder();
            sb.append("package com.automation.generated;\n\n");
            sb.append("import org.openqa.selenium.*;\n");
            sb.append("import org.openqa.selenium.chrome.*;\n");
            sb.append("import org.openqa.selenium.firefox.*;\n");
            sb.append("import org.openqa.selenium.edge.*;\n");
            sb.append("import org.openqa.selenium.support.ui.*;\n");
            sb.append("import org.openqa.selenium.interactions.*;\n");
            sb.append("import org.apache.commons.io.FileUtils;\n");
            sb.append("import java.io.*;\nimport java.time.*;\nimport java.time.format.*;\n\n");
            sb.append("/** Auto-generated by Selenium Automation Studio v2.0 */\n");
            sb.append("public class GeneratedTest {\n\n");
            sb.append("    WebDriver driver;\n");
            sb.append("    int pass = 0, fail = 0;\n");
            sb.append("    String ssDir = \"").append(cfg.getScreenshotDir()).append("\";\n\n");

            sb.append("    public static void main(String[] args) throws Exception {\n");
            sb.append("        new GeneratedTest().execute();\n");
            sb.append("    }\n\n");

            sb.append("    void execute() throws Exception {\n");
            for (String br : browsers) {
                sb.append("        System.out.println(\"===== ").append(br.toUpperCase()).append(" =====\");\n");
                sb.append("        try {\n");
                switch (br.toLowerCase()) {
                    case "firefox":
                        sb.append("            FirefoxOptions o = new FirefoxOptions();\n");
                        if (headless) sb.append("            o.addArguments(\"-headless\");\n");
                        sb.append("            driver = new FirefoxDriver(o);\n");
                        break;
                    case "edge":
                        sb.append("            EdgeOptions o = new EdgeOptions();\n");
                        if (headless) sb.append("            o.addArguments(\"--headless\");\n");
                        sb.append("            driver = new EdgeDriver(o);\n");
                        break;
                    default:
                        sb.append("            ChromeOptions o = new ChromeOptions();\n");
                        if (headless) sb.append("            o.addArguments(\"--headless\", \"--no-sandbox\");\n");
                        sb.append("            driver = new ChromeDriver(o);\n");
                }
                sb.append("            driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(")
                  .append(cfg.getImplicitWait()).append("));\n");
                sb.append("            driver.manage().timeouts().pageLoadTimeout(Duration.ofSeconds(")
                  .append(cfg.getPageLoad()).append("));\n");
                if (maximize) sb.append("            driver.manage().window().maximize();\n");
                else sb.append("            driver.manage().window().setSize(new Dimension(")
                         .append(cfg.getResW()).append(", ").append(cfg.getResH()).append("));\n");
                sb.append("            driver.get(\"").append(cfg.getUrl()).append("\");\n");
                sb.append("            runSteps();\n");
                sb.append("        } finally {\n");
                sb.append("            if (driver != null) driver.quit();\n");
                sb.append("        }\n");
            }
            sb.append("        System.out.println(\"\\n===== Results: PASS=\" + pass + \" FAIL=\" + fail + \" =====\");\n");
            sb.append("    }\n\n");

            sb.append("    void runSteps() throws Exception {\n");
            for (int i = 0; i < steps.size(); i++) {
                TestStep s  = steps.get(i);
                String   a  = s.getAction();
                String   x  = s.getXpath();
                String   v  = s.getValue();
                String   v2 = s.getValue2();
                int      w  = s.getWait();

                sb.append("        // Step ").append(i + 1).append(": ").append(a).append("\n");
                sb.append("        step(\"Step ").append(i + 1).append("\", () -> {\n");
                switch (a) {
                    case "click":
                        sb.append("            driver.findElement(By.xpath(\"").append(esc(x)).append("\")).click();\n");
                        break;
                    case "type":
                        sb.append("            driver.findElement(By.xpath(\"").append(esc(x)).append("\")).sendKeys(\"").append(esc(v)).append("\");\n");
                        break;
                    case "clearField":
                        sb.append("            driver.findElement(By.xpath(\"").append(esc(x)).append("\")).clear();\n");
                        break;
                    case "dropdown":
                        sb.append("            new Select(driver.findElement(By.xpath(\"").append(esc(x)).append("\")))\n");
                        sb.append("                .").append(v.isEmpty() ? "selectByVisibleText" : v).append("(\"").append(esc(v2)).append("\");\n");
                        break;
                    case "getText":
                        sb.append("            System.out.println(\"TEXT: \" + driver.findElement(By.xpath(\"").append(esc(x)).append("\")).getText());\n");
                        break;
                    case "getAttribute":
                        sb.append("            System.out.println(\"ATTR: \" + driver.findElement(By.xpath(\"").append(esc(x)).append("\")).getAttribute(\"").append(esc(v)).append("\"));\n");
                        break;
                    case "verifyText":
                        sb.append("            String t = driver.findElement(By.xpath(\"").append(esc(x)).append("\")).getText();\n");
                        sb.append("            if (!t.equals(\"").append(esc(v)).append("\")) throw new AssertionError(\"Expected: ").append(esc(v)).append(" Got: \" + t);\n");
                        break;
                    case "navigate":
                        sb.append("            driver.get(\"").append(esc(v)).append("\");\n");
                        break;
                    case "screenshot":
                        sb.append("            screenshot(\"").append(esc(v.isEmpty() ? "step_" + (i + 1) : v)).append("\");\n");
                        break;
                    case "scrollTo":
                        sb.append("            ((JavascriptExecutor)driver).executeScript(\"arguments[0].scrollIntoView(true);\",\n");
                        sb.append("                driver.findElement(By.xpath(\"").append(esc(x)).append("\")));\n");
                        break;
                    case "hover":
                        sb.append("            new Actions(driver).moveToElement(\n");
                        sb.append("                driver.findElement(By.xpath(\"").append(esc(x)).append("\"))).perform();\n");
                        break;
                    case "jsClick":
                        sb.append("            ((JavascriptExecutor)driver).executeScript(\"arguments[0].click();\",\n");
                        sb.append("                driver.findElement(By.xpath(\"").append(esc(x)).append("\")));\n");
                        break;
                    case "acceptAlert":
                        sb.append("            driver.switchTo().alert().").append("dismiss".equals(v) ? "dismiss" : "accept").append("();\n");
                        break;
                    case "print":
                        sb.append("            System.out.println(\"[LOG] ").append(esc(v)).append("\");\n");
                        break;
                    case "wait":
                        sb.append("            Thread.sleep(").append(v.isEmpty() ? "1000" : v).append(");\n");
                        break;
                    default:
                        sb.append("            // TODO: action '").append(a).append("' - implement manually\n");
                }
                sb.append("        });\n");
                if (w > 0) sb.append("        Thread.sleep(").append(w).append(");\n");
            }
            sb.append("    }\n\n");

            sb.append("    void step(String name, RunnableStep r) {\n");
            sb.append("        System.out.print(\"[RUN] \" + name + \" ... \");\n");
            sb.append("        try {\n");
            sb.append("            r.run(); pass++;\n");
            sb.append("            System.out.println(\"PASS\");\n");
            sb.append("        } catch (Exception e) {\n");
            sb.append("            fail++;\n");
            sb.append("            System.out.println(\"FAIL: \" + e.getMessage());\n");
            if (autoSS) sb.append("            screenshot(\"FAIL_\" + name.replaceAll(\"[^a-zA-Z0-9]\", \"_\"));\n");
            sb.append("        }\n");
            sb.append("    }\n\n");

            sb.append("    void screenshot(String name) {\n");
            sb.append("        try {\n");
            sb.append("            new File(ssDir).mkdirs();\n");
            sb.append("            String ts = DateTimeFormatter.ofPattern(\"yyyyMMdd_HHmmss\").format(LocalDateTime.now());\n");
            sb.append("            FileUtils.copyFile(\n");
            sb.append("                ((TakesScreenshot) driver).getScreenshotAs(OutputType.FILE),\n");
            sb.append("                new File(ssDir + \"/\" + name + \"_\" + ts + \".png\"));\n");
            sb.append("        } catch (Exception e) {\n");
            sb.append("            System.err.println(\"Screenshot error: \" + e.getMessage());\n");
            sb.append("        }\n");
            sb.append("    }\n\n");

            sb.append("    @FunctionalInterface\n");
            sb.append("    interface RunnableStep { void run() throws Exception; }\n");
            sb.append("}\n");

            return sb.toString();

        } catch (Exception e) {
            return "// Code generation error: " + e.getMessage();
        }
    }

    private static String esc(String s) {
        return s.replace("\\", "\\\\").replace("\"", "\\\"");
    }
}
